window.BOARDS_BLUEPRINT_DATA = [
  {
    "date": "2026-04-06",
    "day": "Monday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "OMM-heavy",
    "type": "School Milestone",
    "obligations": "School diagnostic / 160Q TL assessment",
    "qbankPlan": "School 160Q only",
    "contentFocus": "Light review + build miss tracker",
    "notes": "Anki (light)"
  },
  {
    "date": "2026-04-07",
    "day": "Tuesday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Psych/Derm/Heme Onc",
    "type": "Study",
    "obligations": "Required OMM/BDLS/ACLS blocks",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Heme: anemia framework + RBC disorders",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-08",
    "day": "Wednesday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Psych/Derm/Heme Onc",
    "type": "Study",
    "obligations": "Required OMM / cranial / back pain blocks",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Heme: micro/macro + hemolytic anemias",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-09",
    "day": "Thursday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Psych/Derm/Heme Onc",
    "type": "Study",
    "obligations": "Required OMM/BDLS/ACLS blocks",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Onc: leukemia/lymphoma + coag disorders",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-10",
    "day": "Friday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Psych/Derm/Heme Onc",
    "type": "Study",
    "obligations": "Required OMM/ACLS blocks",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Psych/Derm/Heme Onc mixed pass #1",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-11",
    "day": "Saturday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "UWSA 1 (editable) + full review",
    "contentFocus": "Baseline Step-style predictor",
    "notes": "Keep review high-yield only"
  },
  {
    "date": "2026-04-12",
    "day": "Sunday",
    "week": 1,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review UWSA misses + Anki",
    "notes": "No extra full blocks"
  },
  {
    "date": "2026-04-13",
    "day": "Monday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Psych/Derm/Heme Onc",
    "type": "Study",
    "obligations": "Required OMM/ACLS/checkoffs",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Psych/Derm/Heme Onc weak hits + chemo tox",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-14",
    "day": "Tuesday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Biochem/Immuno/Genetics",
    "type": "Study",
    "obligations": "Required OMM/ACLS/checkoffs",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Biochem: enzymes + core pathways",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-15",
    "day": "Wednesday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Biochem/Immuno/Genetics",
    "type": "Study",
    "obligations": "Required OMM/ACLS/checkoffs",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Immuno: hypersensitivity + immunodeficiencies",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-16",
    "day": "Thursday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Biochem/Immuno/Genetics",
    "type": "Study",
    "obligations": "Required OMM/ACLS/checkoffs",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Genetics: inheritance + chromosomal disorders",
    "notes": "Night: OMM + misses Anki"
  },
  {
    "date": "2026-04-17",
    "day": "Friday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Biochem/Immuno/Genetics",
    "type": "Light Day",
    "obligations": "Keep lighter after school obligations",
    "qbankPlan": "25 TL + UW40 + TL40 + 16 VCOM",
    "contentFocus": "Biochem cleanup + OMM facts",
    "notes": "Shorter evening Anki"
  },
  {
    "date": "2026-04-18",
    "day": "Saturday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "NBME 28 + full review",
    "contentFocus": "Main Step checkpoint #1",
    "notes": "Log top repeated misses"
  },
  {
    "date": "2026-04-19",
    "day": "Sunday",
    "week": 2,
    "phase": "Phase 1: OMM-heavy hybrid",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review NBME 28 + Anki",
    "notes": "Update weak-topic list"
  },
  {
    "date": "2026-04-20",
    "day": "Monday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "Biochem/Immuno/Genetics",
    "type": "Study",
    "obligations": "No required video viewing",
    "qbankPlan": "25 TL + UW40 + TL40 (+ extra block if energy)",
    "contentFocus": "Biochem: vitamins + storage/peroxisomal disease",
    "notes": "Night Anki"
  },
  {
    "date": "2026-04-21",
    "day": "Tuesday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "OMM-heavy",
    "type": "School Milestone",
    "obligations": "PPC/OMM comprehensive final + practical",
    "qbankPlan": "25 TL only",
    "contentFocus": "Light review only after exam",
    "notes": "Night: OMM cleanup + biochem cards"
  },
  {
    "date": "2026-04-22",
    "day": "Wednesday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "Biochem/Immuno/Genetics",
    "type": "Travel",
    "obligations": "Travel to Miami (afternoon flight)",
    "qbankPlan": "25 TL only + flash review",
    "contentFocus": "Immuno/genetics flash review (First Aid + BnB/Anki)",
    "notes": "20–30 min Anki in transit"
  },
  {
    "date": "2026-04-23",
    "day": "Thursday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "Biochem/Immuno/Genetics",
    "type": "Travel",
    "obligations": "Miami — conference / light study only",
    "qbankPlan": "25 TL + opt UW40",
    "contentFocus": "Biochem/Immuno/Genetics cleanup",
    "notes": "Keep it light"
  },
  {
    "date": "2026-04-24",
    "day": "Friday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "Biochem/Immuno/Genetics",
    "type": "Travel",
    "obligations": "Miami — miss school 80Q practice exam; reschedule next week (TBD)",
    "qbankPlan": "25 TL only or travel-light FA/BnB",
    "contentFocus": "Genetics + biochem light review",
    "notes": "No formal exam this day"
  },
  {
    "date": "2026-04-25",
    "day": "Saturday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "Psych/Derm/Heme Onc",
    "type": "Travel",
    "obligations": "Miami — Shoulder360",
    "qbankPlan": "25 TL + opt mixed 40",
    "contentFocus": "Psych/Derm/Heme Onc review cards",
    "notes": "No formal full exam"
  },
  {
    "date": "2026-04-26",
    "day": "Sunday",
    "week": 3,
    "phase": "Phase 2: Main dedicated",
    "system": "Neuro (Optho/ENT)",
    "type": "Review",
    "obligations": "Sunday travel/review",
    "qbankPlan": "25 TL only",
    "contentFocus": "Neuro/optho/ENT flash review + Anki",
    "notes": "Reset for Monday"
  },
  {
    "date": "2026-04-27",
    "day": "Monday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Study",
    "obligations": "Return from Miami",
    "qbankPlan": "25 TL + UW40 + TL40 (+ extra block if energy)",
    "contentFocus": "Repro/Endo: pituitary + adrenal",
    "notes": "Resume normal cadence"
  },
  {
    "date": "2026-04-28",
    "day": "Tuesday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Study",
    "obligations": "Optional placeholder: rescheduled school 80Q exam if assigned",
    "qbankPlan": "25 TL + UW40 + TL40 (+ extra block if energy)",
    "contentFocus": "Repro/Endo: thyroid + parathyroid",
    "notes": "Keep flexible if school exam lands here"
  },
  {
    "date": "2026-04-29",
    "day": "Wednesday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 (+ extra block if energy)",
    "contentFocus": "Repro/Endo: diabetes + insulin",
    "notes": "Night Anki"
  },
  {
    "date": "2026-04-30",
    "day": "Thursday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 (+ extra block if energy)",
    "contentFocus": "Repro/Endo: menstrual/reproductive endo + MEN",
    "notes": "Night Anki"
  },
  {
    "date": "2026-05-01",
    "day": "Friday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Travel",
    "obligations": "Travel to Asheville; military COMSAE only if assigned",
    "qbankPlan": "25 TL only",
    "contentFocus": "Repro light review (FA/BnB)",
    "notes": "Travel day — keep it easy"
  },
  {
    "date": "2026-05-02",
    "day": "Saturday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Travel",
    "obligations": "Asheville trip — light study only",
    "qbankPlan": "25 TL + opt mixed 40",
    "contentFocus": "Endo light review (tables/pathways)",
    "notes": "Light only"
  },
  {
    "date": "2026-05-03",
    "day": "Sunday",
    "week": 4,
    "phase": "Phase 2: Main dedicated",
    "system": "Cardio/Pulm",
    "type": "Review",
    "obligations": "Sunday / return from Asheville",
    "qbankPlan": "25 TL only",
    "contentFocus": "Cardio/Pulm intro (FA/BnB) + Anki",
    "notes": "No extra full blocks"
  },
  {
    "date": "2026-05-04",
    "day": "Monday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Repro/Endo",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Repro/Endo mixed wrap + weak hits",
    "notes": "Main dedicated ramp starts"
  },
  {
    "date": "2026-05-05",
    "day": "Tuesday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Cardio/Pulm",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Cardio: murmurs + valvular disease + HF",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-06",
    "day": "Wednesday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Cardio/Pulm",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Cardio: ischemia + arrhythmias + EKGs",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-07",
    "day": "Thursday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Cardio/Pulm",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Cardio/Pulm: shock + hemodynamics + pulm intro",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-08",
    "day": "Friday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "School practice exam #3 (160Q) / mock COMSAE-USMLE",
    "qbankPlan": "160Q school mock + review",
    "contentFocus": "Review only after exam",
    "notes": "No extra blocks"
  },
  {
    "date": "2026-05-09",
    "day": "Saturday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "NBME 29 + full review",
    "contentFocus": "Main Step checkpoint #2",
    "notes": "Update weak-topic list"
  },
  {
    "date": "2026-05-10",
    "day": "Sunday",
    "week": 5,
    "phase": "Phase 2: Main dedicated",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review NBME 29 + Anki",
    "notes": "Top 20 misses list"
  },
  {
    "date": "2026-05-11",
    "day": "Monday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "Cardio/Pulm",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Cardio/Pulm mixed wrap: PFTs, hypoxemia, pulm disease",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-12",
    "day": "Tuesday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "GI/GU/Renal",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "GI: liver + biliary + jaundice",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-13",
    "day": "Wednesday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "GI/GU/Renal",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "GU/Renal: hematuria + renal masses + pelvic pathology",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-14",
    "day": "Thursday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "GI/GU/Renal",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "GI: bowel habits + abdominal pain + bleeding",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-15",
    "day": "Friday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "GI/GU/Renal",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Renal: acid-base + electrolytes + nephritic/nephrotic",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-16",
    "day": "Saturday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "NBME 30 + full review",
    "contentFocus": "Main Step checkpoint #3",
    "notes": "High-yield review after"
  },
  {
    "date": "2026-05-17",
    "day": "Sunday",
    "week": 6,
    "phase": "Phase 2: Main dedicated",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review NBME 30 + Anki",
    "notes": "Update weak-topic list"
  },
  {
    "date": "2026-05-18",
    "day": "Monday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "GI/GU/Renal",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "GI/GU/Renal mixed wrap + weak hits",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-19",
    "day": "Tuesday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "Neuro (Optho/ENT)",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Neuro: localization + spinal tracts + stroke syndromes",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-20",
    "day": "Wednesday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "Neuro (Optho/ENT)",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Neuro: seizures + movement disorders + headache",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-21",
    "day": "Thursday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "Neuro (Optho/ENT)",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Neuro: cranial nerves + optho + ENT/special senses",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-22",
    "day": "Friday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "Neuro (Optho/ENT)",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Neuro: weakness + NMJ + myopathies",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-23",
    "day": "Saturday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "NBME 31 + full review",
    "contentFocus": "Main Step checkpoint #4",
    "notes": "High-yield review after"
  },
  {
    "date": "2026-05-24",
    "day": "Sunday",
    "week": 7,
    "phase": "Phase 2: Main dedicated",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review NBME 31 + Anki",
    "notes": "Update weak-topic list"
  },
  {
    "date": "2026-05-25",
    "day": "Monday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "Mixed/COMLEX",
    "type": "Light Day",
    "obligations": "Memorial Day / lighter day",
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Ethics/biostats/preventive med + OMM facts",
    "notes": "Light but productive"
  },
  {
    "date": "2026-05-26",
    "day": "Tuesday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Class COMSAE day",
    "qbankPlan": "COMSAE + review",
    "contentFocus": "Flag OMM + system misses",
    "notes": "Review score + action list"
  },
  {
    "date": "2026-05-27",
    "day": "Wednesday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "MSK",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "MSK: trauma + fractures/dislocations + Ortho basics",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-28",
    "day": "Thursday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "MSK",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "MSK: back pain + rheum + upper/lower extremity pearls",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-29",
    "day": "Friday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "MSK",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "MSK: OMM overlap + high-yield cleanup",
    "notes": "Misses to Anki"
  },
  {
    "date": "2026-05-30",
    "day": "Saturday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday COMLEX-style checkpoint",
    "qbankPlan": "TrueLearn full-length / COMLEX SA + review",
    "contentFocus": "Best COMLEX-format rehearsal",
    "notes": "High-yield review only"
  },
  {
    "date": "2026-05-31",
    "day": "Sunday",
    "week": 8,
    "phase": "Phase 2: Main dedicated",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review assessment + Anki",
    "notes": "Prep for COMSAE II week"
  },
  {
    "date": "2026-06-01",
    "day": "Monday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "Mixed/COMLEX",
    "type": "Light Day",
    "obligations": "Lighter pre-COMSAE day",
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "OMM discrete facts + formulas",
    "notes": "Keep fatigue low"
  },
  {
    "date": "2026-06-02",
    "day": "Tuesday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "COMSAE II",
    "qbankPlan": "COMSAE + review",
    "contentFocus": "Use as final COMLEX readiness check",
    "notes": "Action list by evening"
  },
  {
    "date": "2026-06-03",
    "day": "Wednesday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "MSK",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "MSK/OMM overlap + COMSAE misses",
    "notes": "Use as 4th MSK day"
  },
  {
    "date": "2026-06-04",
    "day": "Thursday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "Mixed/COMLEX",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Psych/Derm/Heme Onc + Biochem weak hits",
    "notes": "Night Anki"
  },
  {
    "date": "2026-06-05",
    "day": "Friday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "Mixed/COMLEX",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + UW40 + TL40 + extra mixed 40",
    "contentFocus": "Repro/Endo + GI/GU/Renal cleanup + OMM",
    "notes": "Night Anki"
  },
  {
    "date": "2026-06-06",
    "day": "Saturday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "UWSA 2 + full review",
    "contentFocus": "Final strong Step-style predictor before COMLEX",
    "notes": "Flag only the big misses"
  },
  {
    "date": "2026-06-07",
    "day": "Sunday",
    "week": 9,
    "phase": "Phase 2: Main dedicated",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "25 TL only",
    "contentFocus": "Review UWSA 2 + Anki",
    "notes": "Short list for final COMLEX days"
  },
  {
    "date": "2026-06-08",
    "day": "Monday",
    "week": 10,
    "phase": "Phase 2: Main dedicated",
    "system": "Mixed/COMLEX",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "25 TL + 1-2 mixed blocks max",
    "contentFocus": "Final COMLEX polish: OMM discrete + mixed weak hits",
    "notes": "Night Anki"
  },
  {
    "date": "2026-06-09",
    "day": "Tuesday",
    "week": 10,
    "phase": "Phase 2: Main dedicated",
    "system": "Mixed/COMLEX",
    "type": "Light Day",
    "obligations": "COMSAE II only if needed",
    "qbankPlan": "25 TL + 1-2 mixed blocks max",
    "contentFocus": "OMM facts + formulas + confidence cleanup",
    "notes": "If no COMSAE, keep this light"
  },
  {
    "date": "2026-06-10",
    "day": "Wednesday",
    "week": 10,
    "phase": "Phase 2: Main dedicated",
    "system": "Rest/Reset",
    "type": "Rest",
    "obligations": "No question sets",
    "qbankPlan": "None",
    "contentFocus": "OMM facts / formulas only + rest",
    "notes": "Food, logistics, sleep"
  },
  {
    "date": "2026-06-11",
    "day": "Thursday",
    "week": 10,
    "phase": "Phase 2: Main dedicated",
    "system": "Real Exam",
    "type": "Real Exam",
    "obligations": "COMLEX Level 1",
    "qbankPlan": "Real exam",
    "contentFocus": "Trust your prep",
    "notes": "No study after"
  },
  {
    "date": "2026-06-12",
    "day": "Friday",
    "week": 10,
    "phase": "Phase 3: Step sprint",
    "system": "Rest/Reset",
    "type": "Rest",
    "obligations": "Recovery / reset day",
    "qbankPlan": "AM off; PM build Step-only weak-list",
    "contentFocus": "No OMM after today",
    "notes": "Ease back in"
  },
  {
    "date": "2026-06-13",
    "day": "Saturday",
    "week": 10,
    "phase": "Phase 3: Step sprint",
    "system": "Practice Exam",
    "type": "Practice Exam",
    "obligations": "Saturday self-assessment",
    "qbankPlan": "Free 120 + review",
    "contentFocus": "Best final Step-style dress rehearsal",
    "notes": "Focus on pattern misses only"
  },
  {
    "date": "2026-06-14",
    "day": "Sunday",
    "week": 10,
    "phase": "Phase 3: Step sprint",
    "system": "Review/Anki",
    "type": "Review",
    "obligations": "Sunday review day",
    "qbankPlan": "Optional light Anki only",
    "contentFocus": "Review Free 120 + Anki",
    "notes": "Step-only from here"
  },
  {
    "date": "2026-06-15",
    "day": "Monday",
    "week": 11,
    "phase": "Phase 3: Step sprint",
    "system": "Step Sprint",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "UW40 + UW40 (+ targeted mixed/Anki)",
    "contentFocus": "Biochem/Immuno/Genetics weak hits",
    "notes": "No OMM"
  },
  {
    "date": "2026-06-16",
    "day": "Tuesday",
    "week": 11,
    "phase": "Phase 3: Step sprint",
    "system": "Step Sprint",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "UW40 + UW40 (+ targeted mixed/Anki)",
    "contentFocus": "Psych/Derm/Heme Onc + Repro/Endo weak hits",
    "notes": "No OMM"
  },
  {
    "date": "2026-06-17",
    "day": "Wednesday",
    "week": 11,
    "phase": "Phase 3: Step sprint",
    "system": "Step Sprint",
    "type": "Study",
    "obligations": null,
    "qbankPlan": "UW40 + UW40 (+ targeted mixed/Anki)",
    "contentFocus": "Neuro + Cardio/Pulm cleanup",
    "notes": "No OMM"
  },
  {
    "date": "2026-06-18",
    "day": "Thursday",
    "week": 11,
    "phase": "Phase 3: Step sprint",
    "system": "Step Sprint",
    "type": "Light Day",
    "obligations": "No heavy new learning",
    "qbankPlan": "UW40 max or mixed review only",
    "contentFocus": "GI/GU/Renal + MSK formulas/tables",
    "notes": "Protect energy"
  },
  {
    "date": "2026-06-19",
    "day": "Friday",
    "week": 11,
    "phase": "Phase 3: Step sprint",
    "system": "Rest/Reset",
    "type": "Rest",
    "obligations": "No question sets",
    "qbankPlan": "None",
    "contentFocus": "Rest / food / logistics / walk",
    "notes": "Early night"
  },
  {
    "date": "2026-06-20",
    "day": "Saturday",
    "week": 11,
    "phase": "Phase 3: Step sprint",
    "system": "Real Exam",
    "type": "Real Exam",
    "obligations": "USMLE Step 1",
    "qbankPlan": "Real exam",
    "contentFocus": "Trust your prep",
    "notes": "Done"
  }
];
